sonar.projectKey=bendrerohan060-dot_secure-pipeline-demo
sonar.organization=bendrerohan060-dot

sonar.sources=.
sonar.exclusions=**/node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info